language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: staging-hardiman-web-app
  api_key:
    secure: QQVpXLzNWsTHRRBmoYcsW9KT69jIRcxtsYb9etsnFVId2bvjOhixB9vxkKLZdGh0cM60xpQ+qbMYdO+/DG/lPw9w1AosHa7U025CvOHe78ZPcgSx/8J7n0UXY/RNOa4ye/E46JBFkQWJCds32EdqhDk/gbDEtsi8nwZz2J6HOcsDnBQka/S6LLxyMqtDaD1Wo6zfTti44QwDU+reQuSuFmZIebQ7zWl36g6cdZYpwHdT9+QwBAwtKex2stxed1kbnFQvGS4d0OdO+34bkSJRYA987qrrxVuetCCD7UBdwa6qlRXMYfWvM22I+BCEG8cfbL/hCu1gboOqJOD6g5QVsw4GIiNABs3GQBFjEFLcoH0Ptykt2hTJtBLAWLdkipca+m09Qo1WhMbXx/eNhr/dIEtyrCklpdt0g8iPhtVzdMlTeSbs7cjGoQPDnYgjIsZYyT2bq+HAGq3gz25H+cpADWMaBvP3pYcif3LJQCriljwih5cXGXiikKxGP71RQw9FeSbDJrmTcwgn6jDglhAQlE9576tkwb3qpcGkhpWBuxxCUuxTKnM6AZh1+pfzG+XVKAhYo6EhQh2P/TY5MIKftjqGnOxcqYRXGsSRHQ7uNq7LTT53p59iemvy/P3pS25+rh3a7c7fR8Zyp6TyWYlspEx+pyOOE/MmYpeK4hcCayw=
